services:
  tiktokbackend.api:
    image: ${DOCKER_REGISTRY-}tiktokbackendapi
    build:
      context: .
      dockerfile: TiktokBackend.API/Dockerfile
    ports:
      - "5000:5000"
      - "5001:5001"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Server=sqlserver;Database=TikTok;User Id=sa;Password=YourStrong!Passw0rd;TrustServerCertificate=True
      - Redis__Connection=redis:6379
    depends_on:
      - sqlserver
      - redis
    networks:
      - tiktoknetwork
    restart: on-failure

  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver
    environment:
      SA_PASSWORD: "YourStrong!Passw0rd"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    volumes:
      - sqlvolume:/var/opt/mssql
    networks:
      - tiktoknetwork

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - tiktoknetwork
    restart: always

networks:
  tiktoknetwork:

volumes:
  sqlvolume: